// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeSystemPU.Data;

namespace PracticeSystemPU.Migrations
{
    [DbContext(typeof(PracticeSystemDbContext))]
    partial class PracticeSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Internship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirmId");

                    b.Property<int>("PracticeId");

                    b.Property<int>("Spots");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Practice");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Admin", b =>
                {
                    b.HasBaseType("PracticeSystemPU.Data.Models.User");


                    b.ToTable("Admin");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Firm", b =>
                {
                    b.HasBaseType("PracticeSystemPU.Data.Models.User");

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.ToTable("Firm");

                    b.HasDiscriminator().HasValue("Firm");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Student", b =>
                {
                    b.HasBaseType("PracticeSystemPU.Data.Models.User");

                    b.Property<float>("AvgGrade");

                    b.Property<int>("Fn");

                    b.Property<int>("InternshipId");

                    b.HasIndex("InternshipId");

                    b.ToTable("Student");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Internship", b =>
                {
                    b.HasOne("PracticeSystemPU.Data.Models.Firm", "Firm")
                        .WithMany("Internships")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PracticeSystemPU.Data.Models.Practice", "Practice")
                        .WithMany("Internships")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PracticeSystemPU.Data.Models.Student", b =>
                {
                    b.HasOne("PracticeSystemPU.Data.Models.Internship", "Internship")
                        .WithMany("Students")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
